# Generated by Django 3.1 on 2021-12-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tooloption.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomElement',
            fields=[
                ('DomElement_Id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=120, null=True, verbose_name='section Name')),
                ('subsection', models.CharField(blank=True, max_length=120, null=True, verbose_name='sub-section Name')),
                ('arialabel', models.CharField(blank=True, max_length=300, null=True, verbose_name='Aria label')),
                ('ariahaspopup', models.CharField(blank=True, max_length=300, null=True, verbose_name='Aria has popup')),
                ('color', models.CharField(blank=True, max_length=300, null=True, verbose_name='Element color')),
                ('option', models.CharField(blank=True, max_length=300, null=True, verbose_name='Element option')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Href link')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Element description')),
                ('comp', models.CharField(blank=True, max_length=300, null=True, verbose_name='Material UI Component name')),
                ('elementid', models.CharField(blank=True, default=tooloption.models.GenerateIdForDOMTags, max_length=120, null=True, verbose_name='Dom id')),
                ('elementclass', models.CharField(blank=True, default=tooloption.models.GenerateClassForDOMTags, max_length=120, null=True, verbose_name='Dom class')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Dom_Element_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dom Element info',
                'ordering': ('-created_at',),
            },
        ),
    ]
