# Generated by Django 3.1 on 2021-12-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooloption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domelement',
            name='urlpath',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='section Name'),
        ),
    ]
