# Generated by Django 3.1 on 2021-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooloption', '0002_domelement_urlpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='domelement',
            name='onclick',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='On click send text variable'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='ariahaspopup',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Aria has popup'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='arialabel',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Aria label'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='color',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Element color'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='comp',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Material UI Component name'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='description',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Element description'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=300, null=True, verbose_name='Href link'),
        ),
        migrations.AlterField(
            model_name='domelement',
            name='option',
            field=models.CharField(blank=True, default='None', max_length=300, null=True, verbose_name='Element option'),
        ),
    ]
