# Generated by Django 3.1 on 2021-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='codeentertimer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
