# Generated by Django 3.1 on 2021-12-06 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211111_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserInfo',
            fields=[
                ('NewUserInfo_Id', models.AutoField(primary_key=True, serialize=False)),
                ('IMS_Member_ID', models.IntegerField(blank=True, null=True, verbose_name='IMS Id')),
                ('currentTimeStamp', models.DateField(auto_now=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name')),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes')),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('None', 'N')], default='N', max_length=10, null=True, verbose_name='Gender')),
                ('spouse_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('spouse_IMSID', models.IntegerField(blank=True, null=True, verbose_name='IMS Id')),
                ('father_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('father_IMSID', models.IntegerField(blank=True, null=True, verbose_name='IMS Id')),
                ('mother_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('mother_IMSID', models.IntegerField(blank=True, null=True, verbose_name='IMS Id')),
                ('Satsang_Category', models.CharField(blank=True, choices=[('Satsangi', '1'), ('Premvati', '2'), ('Staff', '3'), ('Gunhavi - Special Guest', '4'), ('None', '5')], default='5', max_length=30, null=True, verbose_name='Satsang Category')),
                ('Mandal', models.CharField(blank=True, choices=[('Premvati', 'P'), ('Sanyukta', 'S'), ('None', 'N')], default='N', max_length=30, null=True, verbose_name='Mandal')),
                ('Address1', models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Address 1')),
                ('Address2', models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Address 2')),
                ('ZipCode', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Zip Code')),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
                ('State', models.CharField(blank=True, max_length=120, null=True, verbose_name='State')),
                ('Country', models.CharField(blank=True, max_length=120, null=True, verbose_name='Country')),
                ('User_image', models.ImageField(default=users.models.default_place_pics, null=True, upload_to='place_pics/User Profile Image/Image')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Info_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New user info',
                'ordering': ('-created_at',),
            },
        ),
    ]
