# Generated by Django 3.1 on 2021-12-06 00:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserinfo',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="User's comments"),
        ),
        migrations.AddField(
            model_name='newuserinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='newuserinfo',
            name='home_phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact home phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='newuserinfo',
            name='mobile_phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact mobile phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='newuserinfo',
            name='vaccinated',
            field=models.CharField(blank=True, choices=[('Yes', 'Y'), ('No', 'N'), ('None', 'NA')], default='NA', max_length=10, null=True, verbose_name='Is user vaccinated?'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="User's extra notes"),
        ),
    ]
