# Generated by Django 3.1 on 2021-12-06 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211205_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserinfo',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('None', 'NA')], default='N', max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Mandal',
            field=models.CharField(blank=True, choices=[('Premvati', 'PRM'), ('Sanyukta', 'SAN'), ('None', 'NA')], default='N', max_length=30, null=True, verbose_name='Mandal'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Satsang_Category',
            field=models.CharField(blank=True, choices=[('Satsangi', 'SAT'), ('Premvati', 'PRM'), ('Staff', 'STF'), ('Gunhavi - Special Guest', 'GUN'), ('None', 'NA')], default='5', max_length=30, null=True, verbose_name='Satsang Category'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Any Comments?'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='father_IMSID',
            field=models.IntegerField(blank=True, null=True, verbose_name="Father's IMS Id"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Father's First Name"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='mother_IMSID',
            field=models.IntegerField(blank=True, null=True, verbose_name="Mother's IMS Id"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Mother's First Name"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes relate to user'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='spouse_IMSID',
            field=models.IntegerField(blank=True, null=True, verbose_name="Spouse's IMS Id"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Spouse's First Name"),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='vaccinated',
            field=models.CharField(blank=True, choices=[('Yes', 'Y'), ('No', 'N'), ('None', 'NA')], default='NA', max_length=10, null=True, verbose_name='Are you vaccinated?'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('Zone_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Zone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Name')),
                ('Direction', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Direction')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zone_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'New zone info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='newuserinfo',
            name='Zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Users_Zone', to='users.zone'),
        ),
    ]
