# Generated by Django 3.1 on 2021-12-07 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211207_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatsangCategory',
            fields=[
                ('SatsangCategory_Id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes relate to Satsang Category')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Satsang_Category_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Satsang Category info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Satsang_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Satsang_Category', to='users.satsangcategory'),
        ),
    ]
