# Generated by Django 3.1 on 2021-12-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211207_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoneleader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='zoneleader',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='zoneleader',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='zoneleader',
            name='prefix',
        ),
        migrations.AddField(
            model_name='zoneleader',
            name='ZoneLeader',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Leader First Name'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Satsang_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Satsang_Category', to='users.satsangcategory'),
        ),
    ]
