# Generated by Django 3.1 on 2021-12-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211207_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='ZoneInfo',
        ),
        migrations.RenameModel(
            old_name='ZoneLeader',
            new_name='ZoneLeaderInfo',
        ),
        migrations.RemoveField(
            model_name='satsangcategory',
            name='Entered_By',
        ),
        migrations.RemoveField(
            model_name='newuserinfo',
            name='so_lead_karyakar',
        ),
        migrations.RemoveField(
            model_name='newuserinfo',
            name='so_lead_karyakar_zone',
        ),
        migrations.CreateModel(
            name='SatsangCategoryInfo',
            fields=[
                ('SatsangCategory_Id', models.AutoField(primary_key=True, serialize=False)),
                ('SatsangCategory', models.CharField(blank=True, max_length=120, null=True, verbose_name='Satsang Category')),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes relate to Satsang Category')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Satsang_Category_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Satsang Category info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MandalInfo',
            fields=[
                ('Mandal_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Mandal', models.CharField(blank=True, max_length=120, null=True, verbose_name='Mandal Name')),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes relate to Mandal')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mandal_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mandal info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Mandal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Mandal', to='users.mandalinfo'),
        ),
        migrations.AlterField(
            model_name='newuserinfo',
            name='Satsang_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Satsang_Category', to='users.satsangcategoryinfo'),
        ),
        migrations.DeleteModel(
            name='Mandal',
        ),
        migrations.DeleteModel(
            name='SatsangCategory',
        ),
    ]
