# Generated by Django 3.1 on 2021-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211207_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoneleaderinfo',
            old_name='ZoneLeader',
            new_name='Zone_Karyakar',
        ),
        migrations.RenameField(
            model_name='zoneleaderinfo',
            old_name='IMS_Member_Id',
            new_name='Zone_Karyakar_IMSId',
        ),
        migrations.AddField(
            model_name='zoneleaderinfo',
            name='Zone_Leader',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Leader First Name'),
        ),
        migrations.AddField(
            model_name='zoneleaderinfo',
            name='Zone_Leader_IMSId',
            field=models.IntegerField(blank=True, null=True, verbose_name='IMS Id'),
        ),
    ]
