# Generated by Django 3.1 on 2021-12-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211207_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSOLeaderInfo',
            fields=[
                ('ZoneSOLeader_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Zone_SO_Leader_IMSId', models.IntegerField(blank=True, null=True, verbose_name='Leader IMS Id')),
                ('Zone_SO_Leader', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Leader First Name')),
                ('Zone_SO_Karyakar_IMSId', models.IntegerField(blank=True, null=True, verbose_name='Karyakar IMS Id')),
                ('Zone_SO_Karyakar', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Leader First Name')),
                ('notes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes relate to user')),
                ('Zone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Name')),
                ('Direction', models.CharField(blank=True, max_length=120, null=True, verbose_name='Zone Direction')),
                ('comments', models.CharField(blank=True, max_length=300, null=True, verbose_name='Any Comments?')),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zone_Leader_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Zone SO Leader info',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='ZoneLeaderInfo',
        ),
    ]
