# Generated by Django 3.1 on 2021-12-12 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211207_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserAddress',
            fields=[
                ('NewUserAddress_Id', models.AutoField(primary_key=True, serialize=False)),
                ('IMS_Member_Id', models.IntegerField(blank=True, null=True, verbose_name='IMS Id')),
                ('Address1', models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Address 1')),
                ('Address2', models.CharField(blank=True, default='NA', max_length=200, null=True, verbose_name='Address 2')),
                ('ZipCode', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Zip Code')),
                ('City', models.CharField(blank=True, max_length=120, null=True, verbose_name='City')),
                ('State', models.CharField(blank=True, max_length=120, null=True, verbose_name='State')),
                ('Country', models.CharField(blank=True, max_length=120, null=True, verbose_name='Country')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='email address')),
                ('mobile_phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact mobile phone number', max_length=31)),
                ('home_phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact home phone number', max_length=31)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Entered_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='User_Address_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Address',
                'ordering': ('-created_at',),
            },
        ),
    ]
